spring.application.name=Idempotency

spring.datasource.url = jdbc:postgresql://localhost:5432/system_design
spring.datasource.username = postgresUser
spring.datasource.password = postgresPassword

spring.jpa.hibernate.ddl-auto = update
spring.jpa.show-sql = true

spring.jackson.time-zone=Asia/Kolkata